### ISSUE TITLE
Specification of minimization 

### ISSUE THREAD

**Issue by tawjaw** [madmann91/minbool#2] opened 2020-09-08 22:20 UTC
Hello. Nice implementation. Simple and modern.

1. What is the limit (maximum number) of input variables the library can handle?

2. What’s the complexity of minimization with respect to the number of input?

Thank you

**Comment by madmann91** [comment] 2020-09-09 05:05
Thank you!
The API itself can represent up to 64 variables if using 64-bit integers (`uint64_t`) to represent `MinTerm`s and inputs. The problem is that this algorithm is slow (complexity-wise) for very complex functions, as it has to perform the Quine-McCluskey algorithm and eliminate variables. I am no expert in boolean minimization, but I know heuristic algorithms that produce answers quicker (at least theoretically) exist. That said, I have tested this program vs an espresso implementation and found that the speed of optimization was similar or faster for this library on the functions I was dealing with (which may be different from yours).

**Comment by madmann91** [comment] 2020-09-09 11:54
I just realized that I forgot to answer your question about the complexity of the Quine-McCluskey algorithm: [It's exponential](https://en.wikipedia.org/wiki/Quine%E2%80%93McCluskey_algorithm). That said, other techniques are based on heuristics and may not give an optimal result.

**Comment by madmann91** [comment] 2020-09-10 05:59
Closing this issue. If those answers did not exactly address your question, feel free to open the issue again.

**Closed as completed by madmann91** 2020-09-10 05:59 UTC
Labels: question

**Comment by tawjaw** [comment] 2020-09-10 19:16
thanks @madmann91 that answers my questions perfectly. 
im not looking for heuristic search techniques.
